Document: git-big-picture
Title: Debian git-big-picture Manual
Author: <insert document author here>
Abstract: This manual describes what git-big-picture is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/git-big-picture/git-big-picture.sgml.gz

Format: postscript
Files: /usr/share/doc/git-big-picture/git-big-picture.ps.gz

Format: text
Files: /usr/share/doc/git-big-picture/git-big-picture.text.gz

Format: HTML
Index: /usr/share/doc/git-big-picture/html/index.html
Files: /usr/share/doc/git-big-picture/html/*.html
